<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Application\Features\User\GetUser\" />
    <Folder Include="Application\Features\User\CreateUser\" />
    <Folder Include="Application\Features\User\SearchUsers\" />
    <Folder Include="Domain\Enums\" />
    <Folder Include="Domain\Events\" />
    <Folder Include="Domain\ValueObjects\" />
    <Folder Include="Presentation\Web\Authentication\ViewModels\" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DayFlow.SharedKernel\DayFlow.SharedKernel.csproj" />
    <ProjectReference Include="..\DayFlow.Web.Common\DayFlow.Web.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Presentation\Resource\IdentityPresentationResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IdentityPresentationResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Presentation\Resource\IdentityPresentationResource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>IdentityPresentationResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
